copy !content.php services.php
copy !content.php services_replacement-windows-installation.php
copy !content.php services_replacement-doors-installation.php
copy !content.php services_window-door-repair.php
copy !content.php services_conservatory-installation.php
copy !content.php services_glass-work.php
copy !content.php services_facias-soffits-guttering.php
copy !content.php case-studies.php
copy !content.php case-studies_door-testimonial-1.php
copy !content.php case-studies_door-testimonial-2.php
copy !content.php exmouth-window-company.php
copy !content.php exmouth-window-company_promise-guarantee.php
copy !content.php contact-dk-windows.php
copy !content.php error404.php

copy !setup.php services-setup.php
copy !setup.php services_replacement-windows-installation-setup.php
copy !setup.php services_replacement-doors-installation-setup.php
copy !setup.php services_window-door-repair-setup.php
copy !setup.php services_conservatory-installation-setup.php
copy !setup.php services_glass-work-setup.php
copy !setup.php services_facias-soffits-guttering-setup.php
copy !setup.php case-studies-setup.php
copy !setup.php case-studies_door-testimonial-1-setup.php
copy !setup.php case-studies_door-testimonial-2-setup.php
copy !setup.php exmouth-window-company-setup.php
copy !setup.php exmouth-window-company_promise-guarantee-setup.php
copy !setup.php contact-dk-windows-setup.php
copy !setup.php error404-setup.php

